##This is Pretty Basic, just don't move stuff around ;)
nickname: Server
irc-network: irc.esper.net
##Dont add the # for the channel separate channels with spaces
channels: changeme onotherchangeme
##On;y det to "true if nickname is registered
isRegistered: false
##Pass only needed if nickname is registered
password: changeme
##For IRC Commands
cmd-token: ^